---

- hosts: all
  become: yes
  tasks:

# Standards: 0.11

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
#
  - name: 1.1.1.1 - Check if CIS modprobe configuration file exists
    stat:
      path: "{{ cis_modprobe_conf_filename }}"
    register: modprobe_1_1_1_1
    tags:
      - level-1
      - section-1
      - "1.1.1.1"
      - scored

  - name: 1.1.1.1 - Display registered value
    debug:
      msg: Output value for {{ modprobe_1_1_1_1 }}
    tags:
      - level-1
      - section-1
      - "1.1.1.1"
      - scored

